// import React, { useState } from "react";
// //import CryptoJS from "crypto-js";
// import "./App.css";
// import AppBar from "@mui/material/AppBar";
// import Box from "@mui/material/Box";
// import Toolbar from "@mui/material/Toolbar";
// import Typography from "@mui/material/Typography";
// import Button from "@mui/material/Button";
// import IconButton from "@mui/material/IconButton";
// import MenuIcon from "@mui/icons-material/Menu";
import { useNavigate } from "react-router-dom";
// //import ButtonGroup from "@mui/material/ButtonGroup";
// const Home = () => {
//   const navigate = useNavigate();
//   const [isHover, setIsHover] = useState(false);

//   const handleMouseEnter = () => {
//     setIsHover(true);
//   };

//   const handleMouseLeave = () => {
//     setIsHover(false);
//   };

//   const handleClick = () => {
//     navigate("/Registation"); // Navigate to '/otherpage'
//   };
//   const handleClickl = () => {
//     navigate("/Login"); // Navigate to '/otherpage'
//   };
//   return (
//     <div className="ap">
//       <div>
//         <Box sx={{ flexGrow: 1 }}>
//           <div>
//             <AppBar
//               position="static"
//               style={{
//                 backgroundColor: isHover
//                   ? "rgba(159, 90, 253, 0.25)"
//                   : "rgba(159, 90, 253, 0)",
//               }}
//               sx={{
//                 position: "absolute",
//                 zindex: 1,
//                 borderRadius: 5,

//                 top: 0,
//               }}
//               onMouseEnter={handleMouseEnter}
//               onMouseLeave={handleMouseLeave}
//             >
//               <Toolbar>
//                 <IconButton
//                   size="large"
//                   edge="start"
//                   color="inherit"
//                   aria-label="menu"
//                   sx={{ mr: 2 }}
//                 >
//                   <MenuIcon />
//                 </IconButton>
//                 <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
//                   <h className="bodyhead">Hand gesture recognition </h>
//                 </Typography>

//                 <Button color="inherit" variant="outlined">
//                   <h className="bodyhead" onClick={handleClickl}>
//                     Login
//                   </h>
//                 </Button>
//                 <div style={{ marginLeft: 10 }}></div>
//                 <div className="vl"></div>
//                 <div style={{ marginLeft: 10 }}></div>
//                 <Button
//                   color="inherit"
//                   variant="outlined"
//                   onClick={handleClick}
//                 >
//                   <h className="bodyhead">Register</h>
//                 </Button>
//               </Toolbar>
//             </AppBar>
//           </div>
//         </Box>
//       </div>
//       <br></br>
//       <br></br>
//       <br></br>
//       <div class="container-fluid">
//         <div class="row">
//           <div class="col-sm-5" style={{ marginLeft: 100 }}>
//             <Box
//               sx={{
//                 height: 550,
//                 //  margin: 4.5,
//                 //  marginLeft: 2,
//                 borderRadius: 5,
//                 border: "red",
//                 backgroundColor: "rgba(0,0,0,0.3)",
//                 opacity: 0.95,
//                 "&:hover": {
//                   backgroundColor: "rgba(0, 0, 0,0.6)",
//                   opacity: 0.99,
//                   boxShadow: "2px 3px 10px #F4AAB9",
//                 },
//               }}
//             >
//               <div class="col-sm-15 text-white" style={{ borderRadius: 10 }}>
//                 <br></br>
//                 <br></br>
//                 <center>
//                   <h className="bodyhead">
//                     Welcome to our platform dedicated to hand gesture
//                     recognition powered by Machine Learning (ML) models
//                     utilizing Surface Electromyography (SEMG) signals. this
//                     website focuses on the calibration and training of sEMG data collected
//                     from sEMG sensors to detect and interpret hand gestures
//                     accurately. and have coustom commands to the gesturesN
//                   </h>
//                   <br></br><br></br>
//                   <h className="bodyhead" >Understanding SEMG Signals:</h><br></br>
//                   <h className="bodyhead">
//                      SEMG signals are electrical
//                     signals generated by the muscles during contractions and
//                     movements. These signals are captured by EMG sensors placed
//                     on the skin's surface, providing insights into muscle
//                     activity and movement patterns. Leveraging SEMG data, our
//                     system interprets these signals to identify and classify
//                     specific hand gestures.
//                   </h>
//                 </center>
//               </div>
//             </Box>
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default Home;

// App.jsx
import React, { useState, useEffect } from "react";
import logo from "./assets/gaia-high-resolution-logo-transparent.png"
import "./App.css";
import videoBg from "./assets/lines_-_5224 (Original).mp4";
import videoBgm from "./assets/vecteezy_plexus-artificial-intelligence-background_12658023.mp4";

import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import { styled } from "@mui/material/styles";
import Paper from "@mui/material/Paper";
import Grid from "@mui/material/Grid";
import { Carousel } from "antd";
import { useParallax } from "react-scroll-parallax";

import "./Fotter.css";
import {
  GithubOutlined,
  LinkedinOutlined,
  InstagramOutlined,
  GoogleOutlined,
  TwitterOutlined,
} from "@ant-design/icons";
import { createFromIconfontCN } from "@ant-design/icons";
import { Space } from "antd";
const IconFont = createFromIconfontCN({
  scriptUrl: "//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js",
});
const contentStyle = {
  height: "300px",
  color: "#fff",
  lineHeight: "160px",
  textAlign: "center",
  background: "#364d79",
};

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: "center",
  color: theme.palette.text.secondary,
}));

const Home = () => {
  const navigate = useNavigate();
  const cat = useParallax({
    scaleX: [0.7, 1, 2, "easeInQuad"],

    scaleY: [1, 1, 2, "easeInQuad"],
  });

  const dog = useParallax({
    scaleX: [0.7, 1, 2, "easeInQuad"],

    scaleY: [1, 1, 2, "easeInQuad"],
  });
  const gradientBackground = {
    // background: "linear-gradient(to right, #ff8a00, #e52e71)",
    // background: "linear-gradient(to right, #bfe9ff, #bfe9ff )",
    background: "linear-gradient(to right, #ff6f72, #f14dfd )",
    WebkitBackgroundClip: "text",
    color: "transparent",
    display: "inline-block",
    height: 100,
  };
  const [isHover, setIsHover] = useState(false);

  const handleMouseEnter = () => {
    setIsHover(true);
  };

  const handleMouseLeave = () => {
    setIsHover(false);
  };
  const [fontSize, setFontSize] = useState(32);
  const [isScrolled, setIsScrolled] = useState(false);
  const [itemFontSize, setItemFontSize] = useState(16);
  const [gridItemWidth, setGridItemWidth] = useState(4);
  const [scrollPosition, setScrollPosition] = useState(0);
  const handleScroll = () => {
    const currentPosition = window.scrollY;
    setScrollPosition(currentPosition);
    const scrollPosition = window.scrollY;
    const scrollRange = 190; // Smaller values make the scrolling more sensitive

    setIsScrolled(scrollPosition > scrollRange);
  };
  useEffect(() => {
    const handleScroll = () => {
      const scrollPosition = window.scrollY;
      // Adjust the values based on your design
      const maxFontSize = 50;
      const minFontSize = 32;
      const scrollRange = 200;

      // Calculate the new font size based on the scroll position
      const newFontSize = Math.max(
        minFontSize,
        maxFontSize -
          (scrollPosition / scrollRange) * (maxFontSize - minFontSize)
      );

      setFontSize(newFontSize);

      // Increase the font size of the Item component as you scroll down
      const maxItemFontSize = 18; // Adjust this value based on your design
      const minItemFontSize = 16; // Adjust this value based on your design
      const itemScrollFontSizeRange = 100;

      const newItemFontSize = Math.min(
        maxItemFontSize,
        minItemFontSize +
          (scrollPosition / itemScrollFontSizeRange) *
            (maxItemFontSize - minItemFontSize)
      );

      setItemFontSize(newItemFontSize);

      const maxGridItemWidth = 6; // Adjust this value based on your design
      const minGridItemWidth = 4; // Adjust this value based on your design
      const gridItemScrollWidthRange = 200;

      const newGridItemWidth = Math.min(
        maxGridItemWidth,
        minGridItemWidth +
          (scrollPosition / gridItemScrollWidthRange) *
            (maxGridItemWidth - minGridItemWidth)
      );

      setGridItemWidth(newGridItemWidth);
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
  useEffect(() => {
    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
  // const pData = [2400, 1398, 9800, 3908, 4800, 3800, 4300];
  // const xLabels = [
  //   'Page A',
  //   'Page B',
  //   'Page C',
  //   'Page D',
  //   'Page E',
  //   'Page F',
  //   'Page G',
  // ];
  const pData = [
    -1, -2, 0, -1, -1, 0, -1, 0, -2, -1, -1, -2, -3, -1, -1, -3, 0, -2, -2, -1,
    2, -1, 0, -1, -3, 0, 0, 0, 0, 0, -3, -3, -1, -3, 0, -1, -2, -2, 0, -2, -1,
    0, 0, -1, -3, -2, -1, 0, -2, 0, -3, 0, -2, 0, 0, 0, 0, -4, -2, -2, -1, -2,
    0, 1, 0, 0, -2, 0, -3, -2, 7, -3, -6, 3, -16, 5, 0, 5, 2, -7, 1, -5, 1, -4,
    -2, 0, -4, 0, 0, -10, 29, -11, 24, -22, -3, 32, 6, 14, -17, -23, 63, -36,
    -22, 32, -100, -78, 54, -8, -31, 70, 36, -39, 118, 41, -60, 44, 50, -38, 89,
    -8, -20, 43, -60, -2, 11, -91, 17, 59, -107, 79, -46, 8, 94, 55, 34, 51,
    -56, 24, 16, -69, 23, -28, -90, 57, -12, 41, 14, 59, -39, -7, 40, 13, -56,
    -38, 21, -10, -16, 111, -28, -32, 127, 31, -81, 28, -40, -1, 41, -12, 17,
    -71, 66, -17, -65, -2, 6, -54, 18, 41, -17, 12, 70, 18, 127, 13, -19, -87,
    -102, 29, 40, -90, -115, 21, 6, 17, 100, -117, 93, 16, 85, -46, 12, 100,
    -25, 13, -37, 8, 57, -30, -15, -81, -28, 13, -126, -22, 30, 42, 5, 58, -57,
    -27, -12, -12, -3, -3, 2, -21, 53, 98, -11, -25, -47, -82, 37, 30, -19, 27,
    21, -58, -7, 52, -9, -2, 39, -49, 15, 44, -114, 46, -2, 10, -8, -30, 50, 26,
    -13, -12, -7, -60, 63, -11, -10, 117, -22, 66, 3, -75, 46, -32, 70, -95,
    -65, -28, -55, 57, 62, -5, 40, -34, 10, -22, 64, 34, 65, -43, 58, -39, 41,
    -1, -53, 48, 2, 12, 60, -44, 27, 57, 21, -55, 20, -59, -15, -48, 33, 47,
    -34, 58, -103, -6, -28, 56, -34, 58, 85, 7, 18, 20, -20, -10, -25, -34, -57,
    46, -109, 51, -15, -21, 29, 56, -28, 3, 64, -50, -25, 54, -1, 69, -92, 19,
    65, 44, -34, -5, -42, -19, 15, -17, 28, -18, -20, 37, -10, -31, 23, 12, -14,
    -33, 13, 3, -14, 2, 7, -2, -1, -9, 5, 0, -4, -7, 0, 7, -5, -9, 4, 0, -6, -5,
    2, 0, -4, 0, -1, -3, 1, -4, 1, 0, -3, 0, -2, 2, -1, -2, 0, 0, -3, -3, 1, -2,
    -2, -3, -1, -2, -2, -1, 0, 0,
  ];

  const xLabels = Array.from({ length: pData.length }, (_, i) => i);

  console.log(pData);
  console.log(xLabels);

 

  const [chartData, setChartData] = useState({
    series: [
      {
        name: "XYZ MOTORS",
        data: pData,
      },
    ],
    options: {
      chart: {
        type: "area",
        height: "100%", // Set the height to 100% to use the full width of the screen
      },
      grid: {
        borderColor: "#e7e7e7",
        row: {
          colors: ["transparent", "transparent"], // takes an array which will be repeated on columns
          opacity: 0.5,
        },
      },
      xaxis: {
        title: {
          text: "index",
        },
      },
      dataLabels: {
        enabled: false,
      },
      markers: {
        size: 0,
      },
      title: {
        text: "sEMG signal",
        align: "left",
      },
      fill: {
        color: "#FFFFFF", // Set the color to white
      },
      stroke: {
        width: 2, // Adjust the thickness of the line
        colors: ["#FFFFFF"], // Set the color to white
      },
    },
  });
  const handleClick = () => {
    navigate("/Registation"); // Navigate to '/otherpage'
  };
  const handleClickl = () => {
    navigate("/Login"); // Navigate to '/otherpage'
  };
  const logoStyle = {
    backgroundImage: `url(${logo})`,
    backgroundSize: 'contain',
    backgroundRepeat  : 'no-repeat',
    backgroundPosition: 'center',
    width: '80px', // Set your desired width
    height: '80px', // Set your desired height
  };
  return (
    <div className="main">
      <video src={videoBg} autoPlay loop muted className="background-video" />
      <div className="main">
        <div className="overlay"></div>
        <video src={videoBgm} autoPlay loop muted />

        <div className="content" style={{ fontSize: `${fontSize}px` }}>
          <hr></hr>
          <br></br>
          <Box sx={{ flexGrow: 1, width: 900, marginLeft: 5 }}>
            <AppBar
              style={{
                borderRadius: "20px 20px 20px 20px",
                backgroundColor: "white",
                boxShadow: isHover ? "0 0 10px rgba(0, 0, 0, 0.5)" : "none",
                opacity: isHover ? 1 : 0.75,
                transition: "box-shadow 0.3s, opacity 0.3s",
                position: "static",
              }}
              // position="fixed"
              onMouseEnter={handleMouseEnter}
              onMouseLeave={handleMouseLeave}
            >
              <Toolbar>
                {/* <IconButton
                  size="large"
                  edge="start"
                  color="inherit"
                  aria-label="menu"
                  sx={{ mr: 2, color: "black" }}
                >
                  <MenuIcon />
                </IconButton> */}
                           <IconButton
                  size="large"
                  edge="start"
                  color="inherit"
                  aria-label="menu"
                  sx={{ mr: 2, ...logoStyle }}
                >
                  
                </IconButton>
                <Typography
                  variant="h6"
                  component="div"
                  sx={{ flexGrow: 1, color: "black" }}
                >
                
                </Typography>
                <Button color="inherit" variant="text" sx={{ color: "black" }} onClick={handleClickl}>
                  <h className="bodyhead">Login</h>
                </Button>
                <div style={{ marginLeft: 10 }}></div>
                <div className="vl"></div>
                <div style={{ marginLeft: 10 }}></div>
                <Button color="inherit" variant="text" sx={{ color: "black" }} onClick={handleClick}>
                  <h className="bodyhead">Register</h>
                </Button>
              </Toolbar>
            </AppBar>
          </Box>
          <br></br>

          <p>
            Welcome To <h style={gradientBackground}>G.A.I.A</h>{" "}
          </p>
          <h style={{ fontSize: fontSize - 10 }}>
            A Gesture AI Assistant and Analyzer
          </h>
        </div>
      </div>
      <div className="main">
        <div className="ove"></div>
        <div className="contentdiv">
          <br></br>
          <br></br>
          <br></br>
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-11" style={{ marginLeft: 40 }}>
                <div className="cat">
                  <Box
                    sx={{
                      height: 380,

                      //  margin: 4.5,
                      //  marginLeft: 2,

                      borderRadius: 5,
                      border: "red",
                      // backgroundColor: "white",

                      "&:hover": {
                        // backgroundColor: "white",

                        boxShadow: "2px 3px 10px #F4AAB9",
                      },
                    }}
                  >
                    <br></br>
                    <br></br>
                    <br></br>
                    <Box sx={{ flexGrow: 1, marginLeft: 10 }} ref={cat.ref}>
                      <Grid container spacing={2}>
                        <div class="col-sm-6">
                          {" "}
                          <div
                            style={{
                              borderRadius: 10,
                              fontSize: `${16}px`,
                            }}
                          >
                            <center>
                              <h1
                                className="bodyhead"
                                style={gradientBackground}
                              >
                                Controll your devises at your finger tips
                              </h1>
                              <br></br>
                              <h className="bodyhead">
                                Welcome to our platform dedicated to hand
                                gesture recognition powered by Machine Learning
                                (ML) models utilizing Surface Electromyography
                                (SEMG) signals.
                              </h>
                              <br></br>

                              <br></br>

                              <div className="cat">
                                <img ref={cat.ref} src="" />
                              </div>
                            </center>
                          </div>
                        </div>
                        <div class="col-sm-6">
                          {" "}
                          <Carousel
                            effect="fade"
                            autoplay
                            autoplaySpeed={2000}
                            prevArrow={<div>Previous</div>}
                            nextArrow={<div>Next</div>}
                          >
                            <div>
                              <img
                                src="https://opengovasia.com/wp-content/uploads/2021/12/algorithm_1270x710.jpg"
                                alt="Image 1"
                                style={{
                                  ...contentStyle,
                                  objectFit: "cover",
                                }}
                              />
                            </div>
                            <div>
                              <img
                                src="https://www.zdnet.com/a/img/resize/e36091cbdd487218cc77f81371993be46792603b/2022/02/25/e8848401-e6c3-4edd-87db-1aca635c1f18/gettyimages-1256306440businessman-pointing-at-hologram-with-icon-on-virtual-screen.jpg?auto=webp&fit=crop&height=675&width=1200"
                                alt="Image 2"
                                style={{
                                  ...contentStyle,
                                  objectFit: "cover",
                                }}
                              />
                            </div>
                            <div>
                              <img
                                src="https://static.c.realme.com/IN/thread/1085800080419586048.jpg"
                                alt="Image 3"
                                style={{
                                  ...contentStyle,
                                  objectFit: "cover",
                                }}
                              />
                            </div>
                            <div>
                              <img
                                src="https://i0.wp.com/scifi.radio/wp-content/uploads/2021/09/hologram-touch_resize_md.jpg?fit=744%2C419&ssl=1"
                                alt="Image 4"
                                style={{
                                  ...contentStyle,
                                  objectFit: "cover",
                                }}
                              />
                            </div>
                          </Carousel>{" "}
                        </div>
                      </Grid>
                    </Box>
                  </Box>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br></br>
      <div className="main">
        <div className="ove"></div>
        <div className="contentdiv">
          <h1 className="bodyhead" ref={dog.ref} style={gradientBackground}>
            Our customization services
          </h1>
          <div className="dog">
            <Box>
              <div class="container-fluid">
                <div class="row">
                  <div class="col-sm-4">
                    <Box
                      sx={{
                        height: 180,
                        width: 390,

                        borderRadius: 5,
                        border: "red",
                        // backgroundColor: "white",

                        "&:hover": {
                          // backgroundColor: "white",

                          boxShadow: "2px 3px 10px #F4AAB9",
                        },
                      }}
                    >
                      <div style={{ marginLeft: "2rem", paddingTop: "1rem" }}>
                        {" "}
                        <h1
                          className="bodyhead"
                          style={{
                            ...gradientBackground,
                            fontSize: 25,
                            height: 50,
                          }}
                        >
                          Personalized Solutions
                        </h1>
                        <br></br>
                        <h>
                          We offer tailored SEMG-based recognition systems to
                          meet specific user needs, ensuring optimal performance
                          and user experience.
                        </h>
                      </div>
                    </Box>
                  </div>
                  <div class="col-sm-4">
                    {" "}
                    <Box
                      sx={{
                        height: 180,
                        width: 390,

                        borderRadius: 5,
                        border: "red",
                        // backgroundColor: "white",

                        "&:hover": {
                          // backgroundColor: "white",

                          boxShadow: "2px 3px 10px #F4AAB9",
                        },
                      }}
                    >
                      <div style={{ marginLeft: "2rem", paddingTop: "1rem" }}>
                        {" "}
                        <h1
                          className="bodyhead"
                          style={{
                            ...gradientBackground,
                            fontSize: 25,
                            height: 50,
                          }}
                        >
                          Advanced Customization
                        </h1>
                        <br></br>
                        <h className="bodyhead">
                          Our team of experts provides advanced customization
                          options, allowing for unique and innovative
                          applications of hand gesture recognition technology.
                        </h>
                      </div>
                    </Box>
                  </div>
                  <div class="col-sm-4">
                    {" "}
                    <Box
                      sx={{
                        height: 180,
                        width: 390,

                        borderRadius: 5,
                        border: "red",
                        // backgroundColor: "white",

                        "&:hover": {
                          // backgroundColor: "white",

                          boxShadow: " 1px 1px 6px 1px #F4AAB9",
                        },
                      }}
                    >
                      <div style={{ marginLeft: "2rem", paddingTop: "1rem" }}>
                        {" "}
                        <h1
                          className="bodyhead"
                          style={{
                            ...gradientBackground,
                            fontSize: 25,
                            height: 50,
                          }}
                        >
                          Integration Assistance
                        </h1>
                        <br></br>
                        <h className="bodyhead">
                          Receive comprehensive support for integrating
                          customized recognition systems into various devices
                          and platfor
                        </h>
                      </div>
                    </Box>
                  </div>
                </div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    marginTop: "1rem",
                  }}
                >
                  <Box
                    sx={{
                      height: 160,
                      width: 950,

                      borderRadius: 5,
                      border: "red",
                      // backgroundColor: "white",

                      "&:hover": {
                        // backgroundColor: "white",

                        boxShadow: "2px 3px 10px #F4AAB9",
                      },
                    }}
                  >
                    <div style={{ marginLeft: "2rem", padding: "0.8rem" }}>
                      {" "}
                      <h1
                        className="bodyhead"
                        style={{
                          ...gradientBackground,
                          fontSize: 25,
                          height: 50,
                        }}
                      >
                        Our calibration services
                      </h1>
                      <br></br>
                      <h className="bodyhead">
                        Our calibration services ensure the accurate and precise
                        functioning of SEMG-based hand gesture recognition
                        systems, optimizing their performance and reliability.
                        We offer calibration solutions for different
                        environments and user requirements.
                      </h>
                    </div>
                  </Box>
                  <Box
                    sx={{
                      borderRadius: 5,

                      display: "flex",
                      flexDirection: "column",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    {" "}
                    <button className="buttona" onClick={handleClickl}>
                      Calibrate
                    </button>
                  </Box>
                </div>
              </div>
            </Box>
            {/* <div id="chart" style={{ color: "red", width: 1000 }}>
            <ReactApexChart
              options={chartData.options}
              series={chartData.series}
              height={350}
              width={1000}
            />
          </div> */}
          </div>
        </div>
      </div>

      <br></br>
      <div className="main">
        <div className="ove"></div>
        <div className="contentdiv">
          <div className="dog"></div>
          <h1 ref={dog.ref} className="bodyhead" style={gradientBackground}>
            Contact us
          </h1>
          <Box
            sx={{
              height: 70,
              width: 315,
              marginTop: -5,
              //  margin: 4.5,
              // marginLeft: 2,
              padding: "1rem",
              borderRadius: 5,
              border: "red",
              // backgroundColor: "white",

              "&:hover": {
                // backgroundColor: "white",

                boxShadow: "2px 3px 10px #F4AAB9",
              },
            }}
          >
            <Space style={{ marginLeft: 0 }}>
              <GoogleOutlined style={{ fontSize: 40 }} />
              <InstagramOutlined style={{ fontSize: 40 }} />
              <LinkedinOutlined style={{ fontSize: 40 }} />
              <GithubOutlined style={{ fontSize: 40 }} />
              <IconFont type="icon-facebook" style={{ fontSize: 40 }} />

              <TwitterOutlined style={{ fontSize: 40 }} />
            </Space>
          </Box>
          <footer class="footer">
            <div class="container-fluid">
              <div class="row">
                <div class="col-sm-4">
                  <Box
                    sx={{
                      height: 180,
                      width: 390,

                      borderRadius: 5,
                      border: "red",
                      // backgroundColor: "white",

                      "&:hover": {
                        // backgroundColor: "white",

                        boxShadow: "2px 3px 10px #F4AAB9",
                      },
                    }}
                  >
                    <div style={{ marginLeft: "2rem", paddingTop: "1rem" }}>
                      {" "}
                      <h1
                        className="bodyhead"
                        style={{
                          ...gradientBackground,
                          fontSize: 25,
                          height: 50,
                          background: "linear-gradient(to right, #bfe9ff, #bfe9ff )",
                        }}
                      >
                        Contact Information
                      </h1>
                      <br></br>
                      <h>Office Address: 123 Street, City, Country</h>
                      <br></br>
                      <h>Email: info@companyname.com</h>
                      <br></br>
                      <h>Phone: +1 (123) 456-7890</h>
                    </div>
                  </Box>
                </div>
                <div class="col-sm-4">
                  {" "}
                  <Box
                    sx={{
                      height: 180,
                      width: 390,

                      borderRadius: 5,
                      border: "red",
                      // backgroundColor: "white",

                      "&:hover": {
                        // backgroundColor: "white",

                        boxShadow: "2px 3px 10px #F4AAB9",
                      },
                    }}
                  >
                    <div style={{ marginLeft: "2rem", paddingTop: "1rem" }}>
                      {" "}
                      <h1
                        className="bodyhead"
                        style={{
                          ...gradientBackground,
                          fontSize: 25,
                          height: 50,
                          background: "linear-gradient(to right, #bfe9ff, #bfe9ff )",
                        }}
                      >
                        Privacy Policy
                      </h1>
                      <br></br>
                      <h className="bodyhead">
                        Data Security: We prioritize the security of your
                        personal information and protect it.
                      </h>
                      <br></br>
                      <h>
                        Cookies Usage: We use cookies to improve user experience
                        and track visits to our site.
                      </h>
                    </div>
                  </Box>
                </div>
                <div class="col-sm-4">
                  {" "}
                  <Box
                    sx={{
                      height: 180,
                      width: 390,

                      borderRadius: 5,
                      border: "red",
                      // backgroundColor: "white",

                      "&:hover": {
                        // backgroundColor: "white",

                        boxShadow: " 1px 1px 6px 1px #F4AAB9",
                      },
                    }}
                  >
                    <div style={{ marginLeft: "2rem", paddingTop: "1rem" }}>
                      {" "}
                      <h1
                        className="bodyhead"
                        style={{
                          ...gradientBackground,
                          fontSize: 25,
                          height: 50,
                          background: "linear-gradient(to right, #bfe9ff, #bfe9ff )",
                        }}
                      >
                        Copyright Information
                      </h1>
                      <br></br>
                      <h className="bodyhead">
                        Ownership: All content, trademarks, and intellectual
                        property displayed on our site are owned by us or used
                        with permission.
                      </h>
                    </div>
                  </Box>
                </div>
              </div>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  marginTop: "1rem",
                }}
              ></div>
            </div>
            <br></br>
            <center> <p>&copy;G.A.I.A | All Rights Reserved</p></center>
           
          </footer>
        </div>
      </div>
    </div>
  );
};

export default Home;
